config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  require 'sidekiq/web'
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :product_reports, only: [] do
    collection do
      get 'ship', to: 'product_reports#ship'
      get 'ship_test', to: 'product_reports#ship_test'
    end
  end

  namespace :planning do
    get 'make', to: 'make'
    get 'pack', to: 'pack'
    get 'workload', to: 'workload'
  end

  namespace :products do
    resources :archives, only: :index
    resources :inventories, only: :index
  end

  resources :products, :only => [:show, :update] do
    resources :fba_allocations, only: [:index]

    member do
      put 'override_quantity'

      get  'edit_ingredients', to: 'ingredients#edit'
      post 'ingredients', to: 'ingredients#update'
    end

    scope module: :products do
      resources :attachments, only: [:index, :create, :destroy]
      resource :inventory, only: :show
      resource :barcode, only: :show
      resource :case_label, only: :show
      resource :note, only: [:show, :edit, :update]
      resources :prime_costs, only: :index
      get 'properties', to: 'properties#show'
      resources :batches, only: :index
      resources :tasks, only: :index
    end
  end

  resources :batches do
    collection do
      get 'chart'
    end
  end

  resources :inventory_items, only: [:update, :destroy]
  resources :inventories, except: [:index]

  resources :material_categories, except: :show
  resources :materials do
    scope module: :materials do
      resources :forecasts, only: :index
      resources :invoices, only: :index
      resources :containers
      resources :transactions, only: :index
      resources :charts, only: :index do
        collection do 
          get 'cost_over_time'
        end
      end
      resources :attachments, only: [:index, :create, :destroy]
      resources :ordering_sizes, only: :index
    end
    get 'edit_sizes'
  end

  resources :vendors

  resources :invoices do
    collection do
      get 'chart'
      get 'vendors_chart'
    end
    put "generate", to: "invoices#generate", on: :collection
    patch "invoice_paid", to: "invoices#invoice_paid", on: :member, as: :paid
    resources :invoice_items, as: 'items', except: [:index] do
      patch 'item_received', on: :member, as: :received
    end
  end

  resources :units

  resources :amazon_shipments, only: [:index, :create, :update, :show]

  resources :tasks, except: :index do
    member do
      put 'start'
      put 'cancel'
    end

    collection do
      get 'make', to: 'tasks#make'
      get 'pack', to: 'tasks#pack'
      get 'current', to: 'tasks#current'
      get 'finished', to: 'tasks#finished'
    end
  end

  get 'reports/inventory_health', to: 'dashboard_reports#inventory_health'
  get 'reports/profit_and_loss',  to: 'dashboard_reports#profit_and_loss'

  namespace :admin do
    resources :users

    resources :zones, only: [:index, :edit, :update]

    resources :dashboard, :only => :index
    get 'fetch_products', to: 'dashboard#fetch_products'

    get 'refresh_fba_allocations', to: 'dashboard#refresh_fba_allocations'

    resource :settings, only: [:show, :edit, :update]
  end

  root to: redirect('tasks/current')
end

app/controllers/planning_controller.rb
# frozen_string_literal: true

class PlanningController < ApplicationController
  def make
    render 'index', locals: {
      presenter: planning_presenter(Zone.make_zone, params)
    }
  end

  def pack
    render 'index', locals: {
      presenter: planning_presenter(Zone.pack_zone, params)
    }
  end

  def workload
    render 'workload', locals: { workload: UserWorkload.new }
  end

  private

  def planning_presenter(zone, params)
    status = params[:status]&.to_sym || :unassigned
    inventory_items = fetch_inventory_items zone, status
    ProductionPlanningPresenter.new inventory_items, zone, status: status
  end

  def fetch_inventory_items(zone, status)
    reports = InventoryItems::ProductionReport.with_status(status)
    InventoryItem.in_zone(zone).active_products
      .joins(:production_report).merge(reports)
      .includes(:zone, :production_report, product: :shipment_report)
      .ordered_by_days_of_cover
  end
end

app/views/planning/_new_task_form.html.haml
.js-new-task-form.modal.fade{ role: "dialog", tabindex: "-1" }
  .modal-dialog.modal-sm{ role: "document" }
    .modal-content
      .modal-header
        %button.close{ type: "button", data: { dismiss: "modal"} }
          %span ×
        %h4.modal-title Assign Task
      .modal-body
        = bootstrap_form_for presenter.new_task_form do |f|
          .error.alert.alert-danger{ 'v-show': 'newTaskForm.error' } {{ newTaskForm.error }}
          = f.hidden_field :inventory_item_id, class: 'js-ii-id', "v-model": 'newTaskForm.inventoryItemId'
          = f.collection_select :user_id, presenter.assignable_users, :id, :display_name
          = f.number_field :quantity_in_zone_units, label: "Quantity", append: presenter.zone_unit_name, class: 'js-quantity', "v-model": 'newTaskForm.quantity'
          = f.text_field :date, data: { :provide => "datepicker", "date-today-highlight" => true }
      .modal-footer
        %button.btn.btn-default{ type: "button", data: { dismiss: "modal" } } Cancel
        %button.btn.btn-primary.js-save{ type: "button", "@click.prevent": "newTaskForm.submit()" } Save

app/views/planning/_record.html.haml
%td.text-left
  = link_or_text ii_presenter.product, current_user.admin?, ii_presenter.product.name
%td.days-of-cover.urgency-color.bold= ii_presenter.product_days_of_cover_hint
%td= ii_presenter.current_inventory_in_main_units
%td= ii_presenter.to_cover_in_main_units
%td= ii_presenter.can_cover_in_main_units
%td= duration ii_presenter.production_time_estimate, include_seconds: false

%td
  -if ii_presenter.assigned.positive?
    - tasks_content = render('planning/tasks', ii_presenter: ii_presenter)
    %span.clickable-text{ data: { toggle: 'popover', content: tasks_content }, role: 'button', tabindex: '0' }
      = ii_presenter.assigned_in_main_units

%td.status
  -if ii_presenter.production_plan_fully_supplied? && ii_presenter.production_fully_assigned?
    %span.label.label-success
      %i.fa.fa-check
      Managed
  -unless ii_presenter.production_fully_assigned?
    %span.label.label-warning Unassigned
  -unless ii_presenter.production_plan_fully_supplied?
    %span.label.label-info{ title: ii_presenter.deficit_ingredient_hint } Low materials

app/views/planning/_records.html.haml
- collection_presenter.inventory_item_presenters.each_with_index do |ii_presenter, index|
  %tr{ class: ii_presenter.urgency_css_class, data: {'ii-id': ii_presenter.inventory_item_id} }
    %td.index= index + 1
    = render 'record', ii_presenter: ii_presenter
    %td.assign
      %a{ href: '#',
        "v-on:click.prevent": "newTaskForm.show(#{ii_presenter.inventory_item_id}, #{ii_presenter.unassigned_in_main_units})" }
        Assign

app/views/planning/_status_pills.html.haml
.row
  .col-md-12
    %ul.nav.nav-pills.small
      %li{ class: presenter.filter_css_class(:unassigned) }
        = link_to 'Unassigned', { status: :unassigned }
      %li{ class: presenter.filter_css_class(:low_supply) }
        = link_to 'Low Materials', { status: :low_supply }
      %li{ class: presenter.filter_css_class(:managed) }
        = link_to 'Managed', { status: :managed }
      %li{ class: presenter.filter_css_class(:all) }
        = link_to 'All', { status: :all }

app/views/planning/_tabs.html.haml
.row
  .col-md-12
    %ul.nav.nav-tabs
      = tab 'Make', planning_make_path, link_options: { class: 'zone-make' }
      = tab 'Pack', planning_pack_path, link_options: { class: 'zone-pack' }
      = tab 'Workload', planning_workload_path

app/views/planning/_tasks.html.haml
%table.table.index-table.tasks
  %tr
    %th
    %th Date
    %th Time
    %th Planned
  - ii_presenter.current_tasks_presenters.each do |task_presenter|
    %tr
      %td= task_presenter.user_nickname
      %td= task_presenter.date
      %td= duration task_presenter.duration_estimate, include_seconds: false
      %td= task_presenter.quantity_in_zone_units

app/views/planning/index.haml
#production-planning
  = render 'new_task_form', presenter: presenter
  = render 'tabs'
  = render 'status_pills', presenter: presenter

  = index_table 'js-production-planning js-reports' do
    %thead
      %tr
        %th
        %th Name
        %th.width-100
          %p Days
          %p of cover
        %th.width-100
          %p Inventory,
          %p= presenter.zone_unit_name
        %th.width-100
          %p Demand,
          %p= presenter.zone_unit_name
        %th.width-100
          %p Production allocation,
          %p= presenter.zone_unit_name
        %th.width-100 Time estimate, hh:mm
        %th.width-100
          %p Planned,
          %p= presenter.zone_unit_name
        %th.width-120 Status
        %th.assign
    %tbody
      = render 'records', collection_presenter: presenter

app/views/planning/workload.html.haml
= render 'tabs'

= index_table do
  %thead
    %tr
      %th
      - workload.users.each do |user|
        %th.width-120= user.nickname
  %tbody
    - workload.dates.each do |date|
      %tr
        %td.index.text-right= date&.to_s(:long)
        -workload.users.each do |user|
          %td= duration workload.workload_for(date, user.id), include_seconds: false