config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  require 'sidekiq/web'
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :product_reports, only: [] do
    collection do
      get 'ship', to: 'product_reports#ship'
      get 'ship_test', to: 'product_reports#ship_test'
    end
  end

  namespace :planning do
    get 'make', to: 'make'
    get 'pack', to: 'pack'
    get 'workload', to: 'workload'
  end

  namespace :products do
    resources :archives, only: :index
    resources :inventories, only: :index
  end

  resources :products, :only => [:show, :update] do
    resources :fba_allocations, only: [:index]

    member do
      put 'override_quantity'

      get  'edit_ingredients', to: 'ingredients#edit'
      post 'ingredients', to: 'ingredients#update'
    end

    scope module: :products do
      resources :attachments, only: [:index, :create, :destroy]
      resource :inventory, only: :show
      resource :barcode, only: :show
      resource :case_label, only: :show
      resource :note, only: [:show, :edit, :update]
      resources :prime_costs, only: :index
      get 'properties', to: 'properties#show'
      resources :batches, only: :index
      resources :tasks, only: :index
    end
  end

  resources :batches do
    collection do
      get 'chart'
    end
  end

  resources :inventory_items, only: [:update, :destroy]
  resources :inventories, except: [:index]

  resources :material_categories, except: :show
  resources :materials do
    scope module: :materials do
      resources :forecasts, only: :index
      resources :invoices, only: :index
      resources :containers
      resources :transactions, only: :index
      resources :charts, only: :index do
        collection do 
          get 'cost_over_time'
        end
      end
      resources :attachments, only: [:index, :create, :destroy]
      resources :ordering_sizes, only: :index
    end
    get 'edit_sizes'
  end

  resources :vendors

  resources :invoices do
    collection do
      get 'chart'
      get 'vendors_chart'
    end
    put "generate", to: "invoices#generate", on: :collection
    patch "invoice_paid", to: "invoices#invoice_paid", on: :member, as: :paid
    resources :invoice_items, as: 'items', except: [:index] do
      patch 'item_received', on: :member, as: :received
    end
  end

  resources :units

  resources :amazon_shipments, only: [:index, :create, :update, :show]

  resources :tasks, except: :index do
    member do
      put 'start'
      put 'cancel'
    end

    collection do
      get 'make', to: 'tasks#make'
      get 'pack', to: 'tasks#pack'
      get 'current', to: 'tasks#current'
      get 'finished', to: 'tasks#finished'
    end
  end

  get 'reports/inventory_health', to: 'dashboard_reports#inventory_health'
  get 'reports/profit_and_loss',  to: 'dashboard_reports#profit_and_loss'

  namespace :admin do
    resources :users

    resources :zones, only: [:index, :edit, :update]

    resources :dashboard, :only => :index
    get 'fetch_products', to: 'dashboard#fetch_products'

    get 'refresh_fba_allocations', to: 'dashboard#refresh_fba_allocations'

    resource :settings, only: [:show, :edit, :update]
  end

  root to: redirect('tasks/current')
end

app/models/invoice_item.rb
# frozen_string_literal: true
# == Schema Information
#
# Table name: invoice_items
#
#  id                    :integer          not null, primary key
#  invoice_id            :integer          not null
#  material_id           :integer
#  pkg_external_name     :string
#  pkg_form              :string
#  pkg_unit_id           :integer
#  pkg_amount            :float
#  pkg_price             :decimal(, )
#  quantity              :integer          default(1), not null
#  total_material_amount :decimal(, )      not null
#  total_price           :decimal(, )      not null
#  batch_number          :string
#  created_at            :datetime
#  updated_at            :datetime
#  received_date         :date
#  expiration_date       :date
#  material_container_id :integer
#
# Foreign Keys
#
#  fk_rails_...  (invoice_id => invoices.id)
#  fk_rails_...  (material_id => materials.id)
#

class InvoiceItem < ApplicationRecord
  belongs_to :invoice
  belongs_to :material
  belongs_to :material_container, dependent: :destroy

  validates :invoice_id, :quantity, presence: true

  scope :ordered_by_invoice_date, -> { includes(:invoice).order('invoices.date DESC') }
  scope :before, ->(date) { ordered_by_invoice_date.where('invoices.date < ?', date) }

  delegate :vendor, :vendor_name, to: :invoice
  delegate :date, :number, to: :invoice, prefix: true
  delegate :total_price_matching?, to: :invoice, prefix: true
  delegate :material_name, :material_unit, :material_unit_id, to: :material_container
  delegate :unit, :unit_id, to: :material_container, prefix: 'container'

  def default_lot_number
    invoice.next_lot_number
  end

  concerning :Prices do
    included do
      before_save :set_totals
    end

    private

    def set_totals
      self.total_material_amount = material_container.amount_in_material_units * quantity
      self.total_price = material_container.price * quantity
    end
  end

  concerning :Status do
    included do
      include ReceivingStatus  #  #received?, #become_received

      scope :pending, -> { where(received_date: nil) }
    end

    def locked?
      received? || invoice.locked?
    end
  end
end

app/controllers/invoice_items_controller.rb
# frozen_string_literal: true
class InvoiceItemsController < ApplicationController
  before_action do
    @invoice = Invoice.find(params[:invoice_id])
  end

  def show
    item = @invoice.items.find params[:id]
    init_presenter(item)
  end

  def new
    item = @invoice.items.build
    item.build_material_container
    init_presenter(item)
  end

  def edit
    item = @invoice.items.find params[:id]
    init_presenter(item)
  end

  def create
    result = actions[:create_item].call invoice_item_params.to_h

    if result.success?
      redirect_to @invoice, notice: 'Line item was successfully created.'
    else
      flash[:error] = result.error_message
      invoice_item = result.entity
      invoice_item.build_material_container
      init_presenter(invoice_item)
      render action: :new
    end
  end

  def update
    item = @invoice.items.find params[:id]
    result = actions[:update_item].call item, invoice_item_params(item).to_h

    if result.success?
      redirect_to @invoice, notice: 'Line item was successfully updated.'
    else
      flash.now[:error] = result.error_message
      init_presenter(result.entity)
      render action: :edit
    end
  end

  def item_received
    item = @invoice.items.find params[:id]
    result = actions[:item_received].call item

    respond_to do |format|
      format.json do
        if result.success?
          render json: { invoice_received: @invoice.received? }, status: :ok
        else
          render json: result.error_message, status: :unprocessable_entity
        end
      end
    end
  end

  def destroy
    item = @invoice.items.find params[:id]
    result = actions[:destroy_item].call item

    if result.success?
      flash[:notice] = 'Line item was deleted'
    else
      flash[:error] = "Failed to destroy line item: #{result.error_message}"
    end
    redirect_to @invoice
  end

  def actions
    { create_item:  InvoiceItems::CreateInvoiceItem.build,
      update_item:  InvoiceItems::UpdateInvoiceItem.build,
      destroy_item: InvoiceItems::DestroyInvoiceItem.build,
      item_received: InvoiceItems::InvoiceItemReceived.build }
  end

  def invoice_item_params(item = nil)
    insensitive_params = [
      material_container: [:external_name, :lot_number, :expiration_date_str]
    ]

    sensitive_params = [
      :invoice_id, :quantity,
      material_container: [:material_id, :external_name,
                           :ordering_size_id, :price,
                           :lot_number, :expiration_date_str]
    ]

    return params.require(:invoice_item).permit(insensitive_params) if item&.locked?
    return params.require(:invoice_item).permit(sensitive_params)
  end

  private

  def init_presenter(invoice_item)
    @presenter = InvoiceItemPresenter.new(invoice_item)
  end
end

app/views/invoice_items/_form.html.haml
- url = presenter.item.new_record? ? invoice_items_path : invoice_item_path(presenter.invoice, presenter.item)
= bootstrap_form_for [presenter.invoice, presenter.item], url: url, label_errors: true do |f|
  = f.hidden_field :invoice_id
  = f.fields_for :material_container, presenter.item.material_container do |ff|
    .js-step-1
      .row
        .col-sm-12
          .control-group
            = ff.collection_select :material_id, presenter.materials_for_selection, :id, :name,
              { include_blank: true },
              {class: 'width-auto js-material-select', disabled: presenter.step_1_disabled?}

    .js-step-2{ class: hidden_if(presenter.step_2_hidden?) }
      .row
        .col-md-6.col-sm-12
          .control-group
            = ff.text_field :external_name, label: "External name"

      - unless presenter.locked?
        .row
          .col-md-3.col-sm-6
            .control-group
              = ff.collection_select :ordering_size_id, presenter.sizes_for_selection, :id, :to_s,
                { label: "Size", label_class: 'required' },
                { class: 'js-ordering-sizes' }

          .col-md-3.col-sm-6
            .control-group
              = ff.number_field :price, label: "Size price", prepend: "$", step: 0.00001

      .row
        .col-md-3.col-sm-6
          .control-group
            = ff.text_field :lot_number, label: "Lot #"

        .col-md-3.col-sm-6
          .control-group
            = ff.text_field :expiration_date_str, label: 'Expiration date', class: 'datepicker'

      - unless presenter.locked?
        .row
          .col-md-3.col-sm-6
            .control-group
              = f.number_field :quantity

      .row
        .col-md-6.col-sm-12
          = form_actions(f)

app/views/invoice_items/edit.html.haml
= page_header "Edit Line Item", icon: 'file-text-o'

= render 'form', presenter: @presenter

.row.danger-zone
  .col-lg-4.col-md-5.col-sm-6
    .panel.panel-default
      .panel-heading.danger
        Danger zone
      .panel-body
        = link_to 'Delete this item', invoice_item_path(@presenter.invoice, @presenter.item), method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure?'}

app/views/invoice_items/new.html.haml
= page_header 'New Line Item', icon: 'file-text-o'

= render 'form', presenter: @presenter