config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  require 'sidekiq/web'
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :product_reports, only: [] do
    collection do
      get 'ship', to: 'product_reports#ship'
      get 'ship_test', to: 'product_reports#ship_test'
    end
  end

  namespace :planning do
    get 'make', to: 'make'
    get 'pack', to: 'pack'
    get 'workload', to: 'workload'
  end

  namespace :products do
    resources :archives, only: :index
    resources :inventories, only: :index
  end

  resources :products, :only => [:show, :update] do
    resources :fba_allocations, only: [:index]

    member do
      put 'override_quantity'

      get  'edit_ingredients', to: 'ingredients#edit'
      post 'ingredients', to: 'ingredients#update'
    end

    scope module: :products do
      resources :attachments, only: [:index, :create, :destroy]
      resource :inventory, only: :show
      resource :barcode, only: :show
      resource :case_label, only: :show
      resource :note, only: [:show, :edit, :update]
      resources :prime_costs, only: :index
      get 'properties', to: 'properties#show'
      resources :batches, only: :index
      resources :tasks, only: :index
    end
  end

  resources :batches do
    collection do
      get 'chart'
    end
  end

  resources :inventory_items, only: [:update, :destroy]
  resources :inventories, except: [:index]

  resources :material_categories, except: :show
  resources :materials do
    scope module: :materials do
      resources :forecasts, only: :index
      resources :invoices, only: :index
      resources :containers
      resources :transactions, only: :index
      resources :charts, only: :index do
        collection do 
          get 'cost_over_time'
        end
      end
      resources :attachments, only: [:index, :create, :destroy]
      resources :ordering_sizes, only: :index
    end
    get 'edit_sizes'
  end

  resources :vendors

  resources :invoices do
    collection do
      get 'chart'
      get 'vendors_chart'
    end
    put "generate", to: "invoices#generate", on: :collection
    patch "invoice_paid", to: "invoices#invoice_paid", on: :member, as: :paid
    resources :invoice_items, as: 'items', except: [:index] do
      patch 'item_received', on: :member, as: :received
    end
  end

  resources :units

  resources :amazon_shipments, only: [:index, :create, :update, :show]

  resources :tasks, except: :index do
    member do
      put 'start'
      put 'cancel'
    end

    collection do
      get 'make', to: 'tasks#make'
      get 'pack', to: 'tasks#pack'
      get 'current', to: 'tasks#current'
      get 'finished', to: 'tasks#finished'
    end
  end

  get 'reports/inventory_health', to: 'dashboard_reports#inventory_health'
  get 'reports/profit_and_loss',  to: 'dashboard_reports#profit_and_loss'

  namespace :admin do
    resources :users

    resources :zones, only: [:index, :edit, :update]

    resources :dashboard, :only => :index
    get 'fetch_products', to: 'dashboard#fetch_products'

    get 'refresh_fba_allocations', to: 'dashboard#refresh_fba_allocations'

    resource :settings, only: [:show, :edit, :update]
  end

  root to: redirect('tasks/current')
end

app/models/concerns/products/financials.rb
# frozen_string_literal: true
module Products
  module Financials
    extend ActiveSupport::Concern

    included do
      has_many :product_cogs_snapshots, dependent: :destroy
    end

    def profit
      return unless selling_price
      selling_price - fee - prime_cost
    end

    def gross_margin
      return unless selling_price&.nonzero? && profit
      (profit * 100 / selling_price).round(2)
    end

    def roi
      return unless prime_cost&.nonzero? && profit
      (profit / prime_cost).round(2)
    end

    def labour_cost
      Rails.cache.fetch ['products', self, 'labour_cost'], expires: 1.hour do
        inventory_items.map(&:labour_cost).compact.sum
      end
    end

    def make_labour_cost
      make_inventory_item&.labour_cost
    end

    def pack_labour_cost
      pack_inventory_item&.labour_cost
    end

    def prime_cost
      Rails.cache.fetch ingredients_cache_key('prime_cost') do
        ingredients.map(&:cost).sum
      end
    end
    alias :cogs :prime_cost

    # For pack zone, includes pack zone ingredients only.
    def zone_cogs(zone)
      Rails.cache.fetch ingredients_cache_key(zone, 'zone_cogs') do
        ingredients_for_zone(zone).map(&:cost).sum
      end
    end

    # For pack zone, includes pack and all previous zones' (make) ingredients.
    def cumulative_cogs(zone)
      Rails.cache.fetch ingredients_cache_key(zone, 'cumulative_cogs') do
        ingredients_up_to_zone(zone).map(&:cost).sum
      end
    end
  end
end

app/models/concerns/products/units_of_measure.rb
# frozen_string_literal: true

# Product is an inventoriable that can be an ingredient of another product.
# Ingredients can (in general) be input in tiny units of measure (e.g. ML) -
# not the main ones (Lbs). Each inventoriable knows how to convert back and forth
# between the units.
# For products that are always in 'Each', this conversion is trivial.
# This module implements the required inventoriable methods for ingredients to work.

module Products
  module UnitsOfMeasure
    extend ActiveSupport::Concern

    def main_unit_name
      Unit.each_piece.name
    end
    alias ingredient_unit_name main_unit_name

    def ingredient_to_main_units(amount)
      amount
    end
  end
end

app/models/inventory.rb
# frozen_string_literal: true
# == Schema Information
#
# Table name: inventories
#
#  id                :integer          not null, primary key
#  inventory_item_id :integer          not null
#  quantity          :decimal(, )      not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
# Foreign Keys
#
#  fk_rails_...  (inventory_item_id => inventory_items.id)
#

class Inventory < ApplicationRecord
  include Logging
  belongs_to :inventory_item

  has_one :product, through: :inventory_item, source: :inventoriable, source_type: 'Product'
  has_one :material, through: :inventory_item, source: :inventoriable, source_type: 'Material'

  has_one :zone, through: :inventory_item
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }

  scope :positive, -> { where('inventories.quantity > 0') }

  delegate :production_order, to: :zone

  delegate :name, to: :inventory_item

  def debit(amount)
    raise ArgumentError, 'Only positive amount is allowed' unless amount > 0
    change_quantity(-amount)
  end

  def credit(amount)
    raise ArgumentError, 'Only positive amount is allowed' unless amount > 0
    change_quantity amount
  end

  private

  def change_quantity(amount)
    with_lock do
      self.quantity += amount
      save!
    end
  end
end

app/models/products/aggregated_stats.rb
# frozen_string_literal: true

# Inventory totals among the given set of products.
module Products
  class AggregatedStats
    attr_reader :products
    attr_reader :stats

    def initialize(products)
      @products = products
      @stats = products.map { |product| Products::ProductInventoryStats.new(product) }
    end

    def average_selling_price
      products.average(:selling_price)
    end

    def total_inventory
      stats.sum(&:total_inventory)
    end

    def total_reserved
      stats.sum(&:reserved)
    end

    def total_inventory_price
      stats.sum(&:total_inventory_price)
    end

    def total_inventory_cogs
      stats.sum(&:total_inventory_cogs)
    end

    def total_inventory_profit
      stats.sum(&:total_inventory_profit)
    end

    def total_reserved_quantity_profit
      stats.sum(&:reserved_quantity_profit)
    end
  end
end

app/controllers/inventories_controller.rb
# frozen_string_literal: true
class InventoriesController < ApplicationController
  def create
    result = actions[:create].call inventory_params
    if result.success?
      respond_with_success
    else
      respond_with_failure result.error_message
    end
  end

  def update
    inventory = Inventory.find params[:id]
    result = actions[:update].call inventory, inventory_params
    if result.success?
      respond_with_success
    else
      respond_with_failure result.error_message
    end
  end

  def actions
    { create: SimpleActions::Create.new(Inventory),
      update: SimpleActions::Update.new(Inventory) }
  end

  def inventory_params
    params.require(:inventory).permit(:quantity)
  end

  private

  def respond_with_success
    respond_to do |format|
      format.json { head :no_content, status: :ok }
    end
  end

  def respond_with_failure(message)
    respond_to do |format|
      format.json { render json: { error: message }, status: :unprocessable_entity }
    end
  end
end

app/controllers/products/archives_controller.rb
# frozen_string_literal: true
module Products
  class ArchivesController < ApplicationController
    def index
      products = Product.inactive.order(:internal_title).includes(:zones)
      @presenters = products.map { |product| ProductPresenter.new product }
    end
  end
end

app/controllers/products/attachments_controller.rb
# frozen_string_literal: true
module Products
  class AttachmentsController < ApplicationController
    def index
      product = Product.find params[:product_id]
      @attachments = product.attachments
      @presenter = ProductPresenter.new product
    end

    def create
      result = actions[:create_attachment].call attachment_params
      respond_to do |format|
        format.json do
          if result.success?
            attachment = result.entity
            render json: { status: :success, preview_url: attachment.preview_url }, status: 200
          else
            render json: { status: :error, error: result.error_message }, status: 500
          end
        end
      end
    end

    def destroy
      product = Product.find params[:product_id]
      attachment = product.attachments.find params[:id]
      result = actions[:destroy_attachment].call attachment
      respond_to do |format|
        format.json do
          if result.success?
            render json: { status: :success }, status: 200
          else
            render json: { status: :error, error: result.error_message }, status: 500
          end
        end
      end
    end

    def actions
      { create_attachment: ProductAttachments::CreateAttachment.new,
        destroy_attachment: SimpleActions::Destroy.new(Attachment) }
    end

    def attachment_params
      params.require(:attachment).permit(:url, :product_id, :mimetype)
    end
  end
end

app/controllers/products/barcodes_controller.rb
# frozen_string_literal: true
module Products
  class BarcodesController < ApplicationController
    def show
      product = Product.find params[:product_id]
      generator = BarcodeGenerator.new
      generator.create_barcode product.title, product.fnsku, "tmp/barcode.pdf"

      respond_to do |format|
        format.pdf do
          pdf_filename = File.join(Rails.root, "tmp/barcode.pdf")
          send_file(pdf_filename, filename: "my.pdf", disposition: 'inline', type: "application/pdf")
        end
      end
    end
  end
end

app/controllers/products/batches_controller.rb
# frozen_string_literal: true
module Products
  class BatchesController < ApplicationController
    def index
      product = Product.includes(:batches => [:zone, :users]).find(params[:product_id])
      @presenter = ProductPresenter.new(product)
    end
  end
end

app/controllers/products/case_labels_controller.rb
# frozen_string_literal: true
module Products
  class CaseLabelsController < ApplicationController
    def show
      product = Product.find params[:product_id]

      filename = actions[:create_label].call product
      respond_to do |format|
        format.pdf do
          downloaded_file_name = "#{product.name.underscore}_label.pdf"
          send_file(filename, filename: downloaded_file_name, disposition: 'inline', type: 'application/pdf')
        end
      end
    end

    def actions
      { create_label: Products::CreateProductCaseLabel.build }
    end
  end
end

app/controllers/products/inventories_controller.rb
# frozen_string_literal: true
module Products
  class InventoriesController < ApplicationController
    def show
      product = Product.includes(
        :inventory_items => [:zone, :production_report, :product, :inventoriable],
        :ingredients => {
          :inventory_item => [
            :production_report, :inventoriable, :inventory,
            :material => [:unit, :ingredient_unit, :category]
          ]
        }
      ).find(params[:product_id])
      @presenter = ProductPresenter.new product
    end

    def index
      zone_id = params[:zone_id]
      @zone = Zone.fetch_or_default zone_id

      products = InventoryItem.active_products.in_zone(@zone).includes(
        :zone, :inventory, :inventoriable, :product => [:shipment_report]
      ).order('products.internal_title')
      @presenters = products.map { |product| InventoryItemPresenter.new(product) }
    end
  end
end

app/controllers/products/media_controller.rb
# frozen_string_literal: true
module Products
  class MediaController < ApplicationController
    def index
      product = Product.find params[:product_id]
      @presenter = ProductPresenter.new product
    end
  end
end

app/controllers/products/notes_controller.rb
# frozen_string_literal: true
module Products
  class NotesController < ApplicationController
    def show
      init_presenter
    end

    def edit
      init_presenter
    end

    def update
      product = Product.find params[:product_id]
      product.notes = params[:product][:notes]
      if product.save
        redirect_to product_note_path(product), notice: "Notes were updated."
      else
        @presenter = ProductPresenter.new product
        render :edit
      end
    end

    private

    def init_presenter
      product = Product.find params[:product_id]
      @presenter = ProductPresenter.new product
    end
  end
end

app/controllers/products/prime_costs_controller.rb
# frozen_string_literal: true
module Products
  class PrimeCostsController < ApplicationController
    def index
      product = Product.find_by id: params[:product_id]
      render(json: { error: 'Product not found' }, status: 404) && return unless product

      snapshots = product.product_cogs_snapshots
                         .final_only
                         .ordered

      chart_presenter = PrimeCostChartPresenter.new product, snapshots
      render json: chart_presenter.chart_data, status: :ok
    end
  end
end

app/controllers/products/properties_controller.rb
# frozen_string_literal: true
module Products
  class PropertiesController < ApplicationController
    def show
      product = Product.find params[:product_id]
      @presenter = ProductPresenter.new(product)
    end
  end
end

app/controllers/products/tasks_controller.rb
# frozen_string_literal: true
module Products
  class TasksController < ApplicationController
    def index
      product = Product.find(params[:product_id])
      @product_presenter = ProductPresenter.new(product)

      tasks = Task.for_product(product).ordered.includes(:user,
        :batch => [:product], :inventory_item => [:zone]).limit(500)
      @task_presenters = tasks.map { |task| TaskPresenter.new(task) }
    end
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true
class ProductsController < ApplicationController
  before_action :find_product, only: [:update, :override_quantity]

  # PUT
  def update
    result = actions[:update_product].call @product, request_params
    respond_to do |format|
      format.html { redirect_to product_properties_path(@product) }
      format.json do
        if result.success?
          head :no_content, status: :ok
        else
          render json: { error: result.error_message }, status: :unprocessable_entity
        end
      end
    end
  end

  # PUT
  def override_quantity
    quantity, shipment_type = parse_override_quantity_params params[:product]
    shipment_item = ShipmentItem.build @product, quantity, shipment_type
    result = actions[:fetch_allocations].call shipment_item
    respond_to do |format|
      format.json do
        if result.success?
          allocations = result.entity.reject(&:empty?)
          presenter = AllocationsSerializer.new allocations
          render json: presenter, status: :ok
        else
          render json: [], status: 500
        end
      end
    end
  end

  def show
    redirect_to product_inventory_path(params[:id])
  end

  def actions
    { update_product: Products::UpdateProduct.build,
      override_product_quantity: Products::OverrideProductQuantity.new,
      fetch_allocations: Products::FetchProductAllocations.build }
  end

  private

  def request_params
    params.require(:product)
          .permit(:to_ship_cases_qty_override, :to_ship_items_qty_override,
                  :internal_title,
                  :items_per_case, :production_buffer_days,
                  :batch_min_quantity, :batch_max_quantity, :fee,
                  :is_active, :shipping_type, zone_ids: [])
  end

  def find_product
    @product = Product.find params[:id]
  end

  def parse_override_quantity_params(product_params)
    quantity_param = product_params.keys.select { |param| param =~ /to_ship_.+_qty_override/ }.first
    quantity = product_params[quantity_param].to_i
    shipment_type = quantity_param.match(/to_ship_(.+)_qty_override/)[1]
    [quantity, shipment_type]
  end
end

app/views/products/inventories/_demand_breakdown.html.haml
%table
  %tbody
    - ii_presenter.as_ingredient_demand_breakdown.each do |key, demand|
      %tr
        %td
          %span= link_or_text key, current_user.admin?, key.name
        %td= integer_with_delimiter demand

app/views/products/inventories/_ingredients_table.html.haml
- ingredient_presenters = product_ii_presenter.ingredient_forecast_presenters

-if ingredient_presenters.any?
  %tr.no-border
    %td.bold{colspan: 2}= zone_label(product_ii_presenter.zone)
    %td{colspan: 10}

  - ingredient_presenters.each do |ingredient_presenter|
    %tr
      %td.text-left= link_to ingredient_presenter.inventory_item_name, ingredient_presenter.inventoriable
      %td.text-right= ingredient_presenter.quantity_with_unit
      %td.text-right= ingredient_presenter.cost_percent
      %td.text-right= number_to_currency ingredient_presenter.cost
      %td.text-right= number_to_currency ingredient_presenter.previous_cost
      %td.text-left= dynamics ingredient_presenter.prime_cost_change_percent
      %td
      %td.text-center
        %span.js-toggled.js-material-units
          = ingredient_presenter.current_inventory_with_unit
        %span.js-toggled.js-product-units.hidden
          = ingredient_presenter.current_inventory_in_products
      -if show_in_process
        %td.text-center
          %span.js-toggled.js-material-units
            = ingredient_presenter.in_process_with_unit
          %span.js-toggled.js-product-units.hidden
            = ingredient_presenter.in_process_products
      %td.text-center
        %span.js-toggled.js-material-units
          = ingredient_presenter.to_cover_with_unit
        %span.js-toggled.js-product-units.hidden
          = ingredient_presenter.to_cover_products
      %td.text-center
        %span.js-toggled.js-material-units
          = ingredient_presenter.can_cover_with_unit
        %span.js-toggled.js-product-units.hidden
          = ingredient_presenter.can_cover_products
      %td.text-center
        %span.red.js-toggled.js-material-units
          = ingredient_presenter.shortfall_with_unit
        %span.red.js-toggled.js-product-units.hidden
          = ingredient_presenter.shortfall_products
        = render 'inventory_items/demand_coverage_indicator', presenter: ingredient_presenter.inventory_item_presenter
  %tr
    %td{colspan: 2}
    %td.text-right.total Subtotal:
    %td.text-right.bold.total= number_to_currency product_ii_presenter.zone_prime_cost
    %td{colspan: 8}

  -unless product_ii_presenter.in_ship_zone?
    %tr.gray
      %td Labor cost
      %td
      %td
      %td.text-right= number_to_currency product_ii_presenter.labour_cost
      %td{colspan: 9}

app/views/products/inventories/_show_financials.html.haml
.panel.panel-default.show-financials
  .panel-heading
    Financials
  .panel-body
    %table
      %tr
        %td COGS:
        %td= number_to_currency product_presenter.prime_cost
      %tr
        %td Labor cost:
        %td= number_to_currency product_presenter.labour_cost
      %tr
        %td Selling price:
        %td= number_to_currency product_presenter.selling_price
      %tr
        %td Fee:
        %td= number_to_currency product_presenter.fee
      %tr
        %td Profit:
        %td= number_to_currency product_presenter.profit
      %tr
        %td Gross margin:
        %td= product_presenter.gross_margin
      %tr
        %td ROI:
        %td= product_presenter.roi

app/views/products/inventories/_show_forecast.html.haml
.panel.panel-default.show-production-forecast
  .panel-heading
    Forecast
  .panel-body
    %table.properties
      %tr
        %td Production buffer:
        %td= product_presenter.production_buffer_days
      %tr
        %td Demand forecasting:
        %td= integer_with_delimiter product_presenter.total_demand
    %br

    %table.table.index-table.forecast
      %thead
        %tr
          %th
          %th Current Inventory
          %th Demand
          %th Production Allocation
      %tbody

        -product_presenter.inventory_item_presenters.each do |ii_presenter|
          %tr
            %td
              .zone-label{class: "zone-#{ii_presenter.zone_slug}"}
                = ii_presenter.zone_name
            %td= integer_with_delimiter ii_presenter.inventory_quantity
            %td= integer_with_delimiter ii_presenter.to_cover
            %td= integer_with_delimiter ii_presenter.can_cover


    - make_ii_presenter = product_presenter.make_inventory_item_presenter
    - if make_ii_presenter&.compound_demand?
      .demand-breakdown
        .header Make demand allocation breakdown:
        = render 'demand_breakdown', ii_presenter: make_ii_presenter

app/views/products/inventories/_show_inventory_section.html.haml
.panel.panel-default.show-product-inventory
  .panel-heading
    Inventory
  .panel-body
    %table.table.index-table
      %tbody
        %tr.separator
          %td{colspan: 2} Local warehouse
          %td.cost-header.text-right Cost

        -if product_presenter.has_make_zone?
          %tr
            %td.width-120
              .zone-label.zone-make Made
            %td.text-right= number_with_delimiter product_presenter.made_inventory_quantity
            %td.text-right= number_to_currency product_presenter.made_inventory_total_cogs

        -if product_presenter.has_pack_zone?
          %tr
            %td.width-120
              .zone-label.zone-pack Packed
            %td.text-right= number_with_delimiter product_presenter.packed_inventory_quantity
            %td.text-right
              = number_to_currency product_presenter.packed_inventory_total_cogs

        %tr.total
          %td.text-right Local total:
          %td.text-right= number_with_delimiter product_presenter.made_plus_packed_quantity
          %td.text-right= number_to_currency product_presenter.made_plus_packed_inventory_total_cogs

        %tr.separator
          %td{colspan: 2}
            %span FBA warehouse
          %td.cost-header.text-right Value

        %tr
          %td.width-120
            .zone-label.zone-ship Shipped
          %td.text-right= number_with_delimiter product_presenter.inbound_shipped
          %td.text-right= number_to_currency product_presenter.inbound_shipped_cost_total

        %tr
          %td.width-120
            .zone-label.zone-fba Fulfillable
          %td.text-right= number_with_delimiter product_presenter.fulfillable
          %td.text-right= number_to_currency product_presenter.fulfillable_cost_total

        %tr.total
          %td.text-right FBA total:
          %td.text-right= number_with_delimiter product_presenter.fba_total
          %td.text-right= number_to_currency product_presenter.fba_cost_total

        %tr.days-of-cover
          %td.text-left{colspan: 3}
            %p
              Reserved:
              %span.bold= number_with_delimiter product_presenter.reserved
            %p
              Days of cover:
              %span.bold= product_presenter.days_of_cover
              %span.gray= product_presenter.days_of_cover_hint

app/views/products/inventories/_show_materials.html.haml
.show-product-ingredients
  .panel.panel-default
    .panel-heading
      %ul.actions.list-inline.list-unstyled.pull-right
        %li= link_to 'Edit', edit_ingredients_product_path(product_presenter.product), class: 'pull-right'
        %li
          .dropdown.js-view-toggler
            %button.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
              %span.js-current Material Units
              %span.caret
            %ul.dropdown-menu
              %li.js-option{ data: { toggle: 'js-material-units' } }
                %a{:href => "#"} Material units
              %li.js-option{ data: { toggle: 'js-product-units' } }
                %a{:href => "#"} Product units
      Materials
      .clearfix

  %table.table.table-hover.full-width
    %thead.light
      %tr
        %th.no-border{colspan: 2}
        %th.text-center{colspan: 4} Costs
        %th.no-border
        %th.text-center{colspan: 5} Production
      %tr.no-border
        %th{colspan: 2}
        %th.text-right %
        %th.text-right Current
        %th.text-right Previous
        %th.text-left Change
        %th.no-border
        %th.text-center Current Inventory
        -if product_presenter.gift_box?
          %th.text-center In Process
        %th.text-center Demand
        %th.text-center Production Allocation
        %th.text-center Shortfall
    %tbody
      - product_presenter.zones.each do |zone|
        = render 'ingredients_table', show_in_process: product_presenter.gift_box?,
          product_ii_presenter: product_presenter.inventory_item_presenter(zone)

      %tr.no-border
        %td{colspan: 13} &nbsp;

      %tr
        %td.no-border{colspan: 2}
        %td.total.text-right.bold Total:
        %td.total.text-right.bold= number_to_currency product_presenter.prime_cost
        %td.no-border{colspan: 8}

app/views/products/inventories/index.html.haml
= page_header do
  %h1
    = zone_label(@zone)
    Inventory

#product-page
  .row
    .col-lg-12
      = index_table 'products-inventory' do
        %thead
          %th.width-70
          %th.width-300 Name
          %th.width-100 Inventory Quantity
          -if @zone.pack?
            %th.width-100 Cases
          %th.width-100 Production units per minute
          %th.width-100 Production setup time (minutes)
        %tbody
          -@presenters.each_with_index do |presenter, index|
            %tr.js-component{ data: { inventory_item_id: presenter.inventory_item_id } }
              %td.grey= index + 1
              %td.text-left= render "products/product_as_icon_and_text", product: presenter.product
              %td= editable_integer presenter.inventory, :quantity, input_options: { min: 0 }
              -if @zone.pack?
                %td= presenter.product_presenter.packed_case_quantity
              %td= editable_integer presenter.inventory_item, :production_units_per_minute, input_options: { min: 0, class: 'xsmall' }
              %td= editable_integer presenter.inventory_item, :production_setup_minutes, input_options: { min: 0, class: 'xsmall' }

app/views/products/inventories/show.html.haml
= render 'products/show_header', product_presenter: @presenter

#product-page
  .row
    .col-lg-4.col-md-5
      = render "show_inventory_section", product_presenter: @presenter
    .col-lg-8.col-md-7
      .row
        .col-lg-8
          = render "show_forecast", product_presenter: @presenter
        .col-lg-4
          = render "show_financials", product_presenter: @presenter

  .row
    .col-lg-12
      .panel.panel-default
        .panel-heading Graph
        .panel-body
          #prime-cost-chart-container.js-prime-cost-history-graph{data: {product_id: @presenter.product_id}}

  .row
    .col-lg-12
      = render "show_materials", product_presenter: @presenter